name: Publish to NPM

on:
  push:
    branches:
      - master # Vérifie bien que ta branche s'appelle master (et pas main)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          # Cette option indique à l'action d'écrire le token dans le .npmrc automatiquement
          scope: '' 

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        # L'argument --access public est vital pour les nouveaux packages
        run: npm publish --access public
        env:
          # C'est cette variable que setup-node utilise pour l'auth
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}