name: Publish to NPM

on:
  push:
    branches:
      - master # ou 'main' selon ton repo

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # Cette étape crée le lien entre ton secret GitHub et NPM
      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        run: npm publish --access public